[package]
name = "image-base64"
version = "0.1.0"
license = "MIT"
description = "Imaging library written in Rust. Provides basic filters and decoders for the most common image formats."
authors = ["katsumeshi <katsumeshi@gmail.com>"]
readme = "README.md"
repository = "https://github.com/katsumeshi/image-base64-rs.git"

[dependencies]
image = "0.12.3"
base64 = "0.4.0"
regex = "0.2.1"
rustc-serialize = "0.3.22"
rust-crypto =  "0.2.36"